Cargo.lock

With 6fa604b64f39a26d1ec4fec26239f04d5a8933b1 this program can now be built with a `stable` version of Rust. This simply bumps the version of `libwdi-sys` (and `wdi`) that are used. With this patch, `bmputil` can be built on stable and no longer requires nightly.

wdi: bump version to build with stable

---

LICENSE
LICENSE-MIT
build.rs
src/bmp.rs
src/elf.rs
src/error.rs
src/main.rs
src/usb.rs
src/windows.rs

In this PR we address the missing licensing for the contents of the repository. After having a conversation with Qyriad we came to the agreement implemented here that the code's written by her, but copyright 1bitsquared, using the dual MIT and Apache 2.0 licenses.
Fixes https://github.com/blackmagic-debug/bmputil/issues/5

Fix: missing licensing

---

Cargo.lock
Cargo.toml
src/bmp.rs
src/error.rs
src/main.rs

This PR updates the project dependencies, and implements support for using other bootloaders with the tool - such as the one built-in to some STM32's such as used on blackpill, and dragonBoot.
This experimentally opens up the option for super fast update times on the order of 7s for a full Flash update.

Feature: other bootloader support

---

Cargo.lock
Cargo.toml

In this PR we move bmputil from a Git dependency on wdi-rs/libwdi-sys to their crates.io counterparts now they have been published.
This clears the way for the tool to be published once some niggles have been sorted out and fixed.

Fix: git dependencies

---

Cargo.lock
Cargo.toml
src/bmp.rs
src/main.rs

This PR updates the Clap crate from 3 => 4, solving the `atty` dependabot problem and clearing the way for the tool to be published to crates.io soon.
This is with thanks to Amy for helping us complete the conversion and figure out all the ways things got broken along the way.

Fix: update clap

---

README.md

Just some minor updates to the README now that packages are available on crates.io and built for each release. Hopefully, this will make it easier for folk to know where to find things and not turn people with issues against rust away.
I left the comment about automatic driver installation being experimental on windows, as I'm not sure if that has changed (though it has worked fine for me whenever I've tried it (not very often :sweat_smile:).
Glad to adjust anything if you want it changed.
Thanks!

misc: Updated README for binaries and crates.io

---

Cargo.lock

This PR updates the Cargo lock file as our dependencies have become outdated again.

Fix: Outdated dependencies

---

Cargo.lock

This partially fixes #18, but the release archive still needs correcting

cargo: fix unmatched bmputil version in cargo lock

---

Cargo.lock
Cargo.toml

This PR updates the Cargo lock file and our dependencies to try and stay ahead of the updates curve a little.
This change set includes a bump to the utility version number as it's intended to go straight from merge to publication.

Fix: Cargo updates

---

.gitignore
.vscode/settings.json
Cargo.lock
Cargo.toml

In this PR we update all the dependencies once more with the intention of solving the build problems v0.1.3 now has with the DFU crates due to improper versioning on those dependencies.
dfu-core released breaking changes in v0.7.0 and dfu-libusb released the matching patches in v0.5.3 as a revision release of v0.5.2. This, understandably, made cargo extremely grumpy when trying to solve the dependency changes per the pinning - using the newer dfu-libusb was allowed because it's a revision release, but the newer dfu-core was not because that's a minor and we pin down to the revision.
With both properly upgraded in sync, that solves the build problems.

Fix: Updated dependencies

---

Cargo.lock
Cargo.toml
build.rs
src/bmp.rs
src/error.rs
src/flasher.rs
src/usb.rs

In this PR we move the tool from rusb and the underlying library libusb, which has been a good base but has problems which really need solving. As the all-Rust USB library, nusb became an obvious choice, so as dfu-nusb exists, we are moving the tool over to this.
This PR maintains full function of the tool on the big 3 OSes, however it is a rough and ready conversion and there are still quirks that need addressing - as outlined below:
Linux needs the now consistent device disconnection catching and silencing from the end of the cycle as this is expected due to the device rebooting on conclusion of the cycle.
Windows also needs this same condition handling, only there it shows up as an endpoint STALL to be caught and burred. This is at least now consistent however, so we can do that.
macOS …

Feature: Switch rusb to nusb

---

Cargo.lock
Cargo.toml
src/bin/bmputil-cli.rs
src/bmp.rs
src/elf.rs
src/flasher.rs
src/metadata/mod.rs
src/metadata/structs.rs
src/switcher.rs
src/usb.rs
src/windows.rs

In this PR we replace most of the error handling mechanisms in the utility with color-eyre's error handling type - this nets us a large improvement in error output and makes diving the cause of an error differently interesting.
Generally, though, this seems to be a net win as we get the standard downcast<>() call for converting error types to more specific ones in error mapping situations, and the possibility of arbitrary appropriate error texts generated where the errors occur while dealing with external error types transparently and providing line number information for where things went wrong in a nice friendly error display block.
This PR also rearranges a portion of the download and reboot logic for a probe to suppress spurious post-download errors effectively.

Feature: color-eyre error handling

---

src/bin/bmputil-cli.rs
src/bmp.rs
src/error.rs
src/flasher.rs
src/lib.rs
src/switcher.rs

In this PR we aim to improve the user experience to make the download process smoother and suppress errors that are part of normal operation due to how the OS stack handles a device disappearing from a control request.
This should make error reports more useful and readable, this should also make them only occur on exceptional behaviour and real errors. This PR restores full function of the tool on macOS which was getting punked by spurious errors.

Fix: Improved download UX

---

Cargo.lock
Cargo.toml
src/docs_viewer.rs
src/firmware_selector.rs
src/lib.rs
src/switcher.rs

In this PR we implement a better firmware selection system for multi-variant firmware.
The way this works is that after picking a firmware variant from the list, the user is presented with a secondary action menu - do they want to Flash the firmware on their probe, view documentation about the variant, or pick a different variant; this is handled by a small FSM so they can go back and forth between the variant list and action menu as much as they like.
If the user picks the documentation, the utility downloads a Markdown file co-located with the firmware .elf and switches into a ratatui-based TUI to display it with scrolling etc - when they get done, they can tap `q` to get back to the action menu and either Flash the selection or pick something else. A user can always cancel with `q` at …

Feature: Better firmware selection

---

src/flasher.rs

In this PR we expand the STALL error suppression to all OSes to address an issue reported on Discord shortly after the v1.0.0-rc.1 release.
In this report, the user got a spurious STALL error from their probe as it rebooted back from the bootloader into the new firmware. Linux was the last supported OS for which this was not suppressed.

Fix: spurious STALL errors under Linux

---

README.md

In this PR we overhaul the README for the project which also serves as the crates.io project blurb and docs.rs cover page.
In this overhaul, we aim to update the installation and build instructions, improve the description of what the tool aims to do and achieve, and the factuality of the tool's status. We also remove reference to the tool being experimental as it's been reasonably well tested at this point and should not be considered experimental any more, given we are aiming to do a v1.0.0 release.

Feature: Improved project README

---

Cargo.lock
Cargo.toml
src/bin/bmputil-cli.rs
src/bmp.rs
src/flasher.rs
src/lib.rs
src/metadata/structs.rs
src/probe_identity.rs
src/switcher.rs
tests/probe_identity.rs

In this PR we first convert the CLI from a text-based old style Clap parser, to clap-derive based structures. We then restructure the interface per the internal notes to provide a more consistent command line experience and make space for future tool functionality.
This PR introduces full parsing for version numbers from the firmware and metadata, allowing them to be properly and accurately compared. This allows the tool to determine if the probe is running the most up-to-date release firmware or not automatically and upgrade the probe accordingly via `bmputil-cli probe update`. This also fixes a long standing bug in the post-Flash validation step which caused havoc if the programming process actually failed and the tool didn't realise.
There is a known issue that was introduced with #36 …

Feature: CLI Restructure

---

src/bin/bmputil-cli.rs
src/probe_identity.rs
src/switcher.rs
tests/probe_identity.rs

In this PR we solve the problems with handling bootloader identities that #36 highlighted was not well dealt with or clear to understand.
This was triggered by finding that commands such as `probe reboot` would not find the probe in its bootloader after the first phase of restarting the probe was complete. This was a direct consequence of the ProbeIdentity code considering the bootloader product string to be invalid and throwing a fit. The fix in this PR is not comprehensive, but it should serve as a solid extendable base.
With this, all previously working bootloaders for the native probe work properly again save for a second bug found in the DFU reboot handling for going from bootloader back to firmware for non-DfuSe bootloaders.

Fix: Bootloader product string parsing

---

README.md

Now that our release artifacts are renamed, `binstall` can be used instead of `install`. Which in most cases should help users avoid building the tool from the sources. It is mainly beneficial on Windows that has very tricky build dependencies.

README: Updated installation instructions to point people towards binstall

---

README.md

The version must not contain the `v` otherwise binstall will complain about an unexpected character.

Corrected version in the rc install instructions

---

Cargo.lock
Cargo.toml

We did not intend to depend on openssl, but it was part of the default feature set of reqwest. We are using rusttls instead. To get rid of the dependency we have to disable default features and enable what we want manually.

reqwest: Disable openssl dependency.

---

src/bin/bmputil-cli.rs
src/bmp_matcher.rs
src/metadata/firmware_download.rs
src/serial/remote/mod.rs
src/serial/remote/protocol_v0.rs
src/serial/remote/protocol_v1.rs
src/serial/remote/protocol_v2.rs
src/serial/remote/protocol_v3.rs
src/serial/remote/protocol_v4.rs

As per #46 , my attempt to take a stab on this.
- As discussed, this command should only attempt a call on v2 and higher.
- As discussed, makes only sense to target 1 BMP
Open question: 
- `println!("Device target power state: {}", power);`, do we want to return `println!` or `info!` here?

CLI Feature: target power 

---

.github/FUNDING.yml
.github/workflows/build-linux.yml
.github/workflows/build-macos.yml
.github/workflows/build-windows.yml
src/error.rs

In this PR we introduce a set of flows for doing continuous integration on the tool to detect issues early and automatically. This includes GHA flows for Linux, macOS and Windows and aims to cover builds for all flavours of target environment (x86{,_64} and AArch64).

Feature: GitHub Actions-based CI
